apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cg67
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cg67
    app.kubernetes.io/part-of: tkrw-pr712-0075-0045-app
  name: devfile-sample-cg67
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cg67
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cg67
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-cg67@sha256:638073b4f88e0d53b5bc4f79be18be485771dc1a2b745ec09e7b3ea61c82aa52
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
